fundoonote/Users/urls.py
from django.conf.urls import include,url
from . import views
from django.urls import path
from django.contrib import admin

app_name = 'Users'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/$', views.register, name='register'), # url for register
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    views.activate, name='activate'),# url activate the user registration
    url('rest_login/', views.RestLogin.as_view(), name='rest_login'),
    # list of Notes URL
    path("Notes/List/", views.NotesList.as_view(), name="note_list"),
    path("Notes/Detail/<int:pk>/", views.NotesDetail.as_view(), name="note_detail"),
    path("Notes/Create/", views.CreateNotes.as_view(), name="note"),
    path("Notes/Delete/<int:pk>/", views.NotesDelete.as_view(),name='delete'),
    path("Notes/Trash/<int:pk>/", views.TrashView.as_view(), name='trash'),
    path("Notes/Archive/<int:pk>/", views.ArchiveNotes.as_view(), name='archive'),
    path("Notes/ArchiveList/", views.ArchiveList.as_view(), name='archive'),
    path("Notes/Reminder/<int:pk>/", views.ReminderNotes.as_view(), name='reminder'),
    path("Notes/TrashList/<trash>", views.TrashList.as_view(), name='trash_list'),
    path("Notes/Pagination/", views.NotesListPage.as_view(), name="note_list"),

    # List of label URL
    path("Label/List/", views.LabelList.as_view(), name="label_list"),
    path("Label/Detail/<int:pk>/", views.LabelDetail.as_view(), name="label_detail"),
    path("Label/Create/", views.CreateLabel.as_view(), name="label"),
    path("Label/Delete/<int:pk>/", views.LabelDelete.as_view(), name='delete'),
    url(r'^search/', views.search, name='search'),
]

fundoonote/fundooapp/urls.py
from allauth.account.views import ConfirmEmailView
from django.conf.urls import include,url

from . import views
from django.urls import path
from django.contrib import admin

app_name = 'fundooapp'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/$', views.register, name='register'), # url for register
    url(r'user_login/', views.user_login, name='login'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    views.activate, name='activate'),# url activate the user registration
    path(r'Notes/List/', views.NotesList.as_view(), name="note_list"),
    path(r'Notes/UserList/', views.NotesListUser.as_view(), name='note_list_user'),
    path(r'Notes/Detail/<int:pk>/', views.NotesDetail.as_view(), name="note_detail"),
    path(r'Notes/Create/', views.CreateNotes.as_view(), name="note_create"),
    path(r'Notes/Delete/<int:pk>/', views.NotesDelete.as_view(),name='note_delete'),
    path(r'Notes/Update/<int:pk>/', views.NotesUpdate.as_view(), name='note_update'),
    path(r'Notes/Trash/<int:pk>/', views.TrashView.as_view(), name='note_trash'),
    path(r'Notes/Archive/<int:pk>/', views.ArchiveNotes.as_view(), name='note_archive'),
    path(r'Notes/ArchiveList/', views.ArchiveList.as_view(), name='note_archive_list'),
    path(r'Notes/Reminder/<int:pk>/', views.ReminderNotes.as_view(), name='note_reminder'),
    path(r'Notes/TrashList/', views.TrashList.as_view(), name='trash_list'),
    path(r'Notes/Pagination/', views.NotesListPage.as_view(), name="note_page"),
    path(r'Label/List/', views.LabelList.as_view(), name="label_list"),
    path(r'Label/Detail/<int:pk>/', views.LabelUpdateDetail.as_view(), name="label_detail"),
    path(r'Label/Create/', views.CreateLabel.as_view(), name="label_create"),
    path(r'Label/Delete/<int:pk>/', views.LabelDelete.as_view(), name='delete_label'),
    path(r'Label/Pagination/',views.LabelListPage.as_view(), name="label_page"),
    path(r'Label/get_label_note/<int:pk>/', views.LabelFromNotes.as_view(), name="label_page"),
    path(r'aws/create/', views.CreateBucket.as_view(), name='create_bucket'),
    path(r'aws/delete/<int:pk>/', views.DeleteBucket.as_view(), name='delete_bucket'),
    path(r'aws/List/', views.BucketList.as_view(), name="bucket_list"),
    path(r'aws/upload_s3/<int:pk>/', views.s3_upload, name='upload_image'),
    path(r'aws/object/<int:pk>/', views.GetBucketObject.as_view(), name='get_object'),
    path(r'Search/user/', views.UserListView.as_view(), name="user"),
    path(r'Search/notes/',views.NotesListView.as_view(), name="note"),
    path(r'search/', views.search, name='search'),
    path(r'rest-auth/', include('rest_auth.urls')),
    path(r'rest-auth/',ConfirmEmailView.as_view(),name="view"),
    path(r'rest_api/register/', views.RestUserRegister.as_view(), name='rest_register'),
    path(r'rest_api/login/', views.Login.as_view(), name='rest_login'),
]

fundoonote/fundoonote/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view
from rest_framework_simplejwt import views as jwt_views
from fundooapp import views
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet) # register the view_set to display the all users
router.register(r'Search/elastic_search',views.NotesDocumentViewSet,basename='elastic_search')
schema_view = get_schema_view(title='Pastebin API')
urlpatterns = [
    url('^schema/', schema_view),
    url('^', include('fundooapp.urls')), # include the all app urls in project urls
    url(r'^register/$', views.register, name='register'),  # url for register
    url(r'^admin/', admin.site.urls), # admin login urls in rest Format
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^$', views.home, name='home'), # index url is call the template
    url(r'^enter/', views.enter, name='enter'), # enter is html template urls
    url(r'^', include(router.urls)), # include the router url to use the display all users
    url(r'^api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^get_users/',views.get_users), # this view_url is display the all users in JSOn format
    url(r'^social-auth/', include('social_django.urls', namespace="social")),
    url(r'^',include('rest_framework.urls', namespace='rest_framework')),
    url(r'^swagger/$', get_swagger_view(title='API Docs'), name='api_docs'), # swagger
    url(r'^api/', include_docs_urls(title='Notes API'), name='api'), # CoreApi
    url(r'^',include('django.contrib.auth.urls')),


]

fundoonote/fundooapp/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm): # UserForm is created the form
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(max_length=200)
    class Meta:
        model = User
        fields = ('username','first_name','last_name','password', 'email')

fundoonote/fundooapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
import logging
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django_elasticsearch_dsl_drf.constants import LOOKUP_FILTER_RANGE,\
     LOOKUP_QUERY_IN, LOOKUP_QUERY_GT, \
     LOOKUP_QUERY_GTE, LOOKUP_QUERY_LT, LOOKUP_QUERY_LTE
from django_elasticsearch_dsl_drf.filter_backends import FilteringFilterBackend, \
     OrderingFilterBackend, DefaultOrderingFilterBackend,\
     CompoundSearchFilterBackend, FunctionalSuggesterFilterBackend
from django_elasticsearch_dsl_drf.viewsets import DocumentViewSet
from rest_framework.generics import CreateAPIView, ListCreateAPIView
from rest_framework import viewsets, generics, status
from rest_framework.pagination import PageNumberPagination, LimitOffsetPagination
from rest_framework import filters
from django.db.models import Q
from .serializers import LoginSerializer, RegisterSerializer, AWSModelSerializer,\
      NotesDocumentSerializer, UserDetailSerializer
from .redis import RedisMethods
from .forms import UserForm
from .documents import NotesDocument
import boto3
from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from .models import Notes, Label, AWSModel
from .serializers import NotesSerializer, LabelSerializer
import pickle
from django.core.mail import send_mail
import json
from django_filters.rest_framework import DjangoFilterBackend
import jwt
from .service import BotoService
from .decorators import app_login_required, app_pk_login_required
from .tokens import account_activation_token

log = logging.getLogger(__name__)
redis_obj = RedisMethods()
boto = BotoService()

def home(request):
    """this method is used to display the home page"""
    return render(request, 'fundooapp/home.html', {})


def enter(request):
    """this method is used to enter the fundooapp"""
    return render(request, 'fundooapp/index.html', {})

"""only after login of user this method can be called"""
def user_logout(request):  # this method is used to logout
    redis_obj.flush()               # before logout we flush the token
    print(redis_obj.get_value('token_key')) # check the token is flush or not
    logout(request)
    return HttpResponseRedirect(reverse('home')) # after logout user reverse the index


"""this method is used to signup the user"""
def register(request):      # this method is used to signup the user
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            mail_subject = 'Activate your blog account.'
            message = render_to_string('fundooapp/acc_active_email.html', {
                'user': user,
                'domain': 'localhost:8000',
                # takes user id and generates the base64 code(uidb64)
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                # Here we receive uidb64, token. By using the "urlsafe_base64_decode"
                # we decode the base64 encoded uidb64 user id.
                # We query the database with user id to get user
                'token': account_activation_token.make_token(user),
                # takes the user object and generates the onetime usable token for the user(token)
            })
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')

    else:
        user_form = UserForm()
    return render(request, 'fundooapp/registration.html', {'user_form': user_form})

@csrf_exempt
def user_login(request):
    # this is a POST request we need to process the form data
    if request.method == 'POST':
        try:
            response = {
                "message": "something bad happened",
                "data": {},
                "success": False
            }
            username = request.POST.get('username')
            password = request.POST.get('password')
            if username is None and password is None:
                raise Exception('Username and password is required')
            # authentication of user name and password
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    payload = {'username': username, 'password': password}
                    jwt_token = {
                        'token': jwt.encode(payload, "Cypher", algorithm='HS256').decode('utf-8')
                    }
                    print(jwt_token)  # print JWT Token
                    """ JWT token stored in cache"""
                    token = jwt_token['token']
                    print(token)
                    redis_obj.set_value('token_key', token)  # set the token in redis cache
                    # get the value of token from cache
                    token_val = redis_obj.get_value('token_key')
                    print("Display The Tokens using get_token()")
                    print(token_val)  # print the cache token
                    print("Display the length of Token")
                    login(request, user)
                    print(user.username)
                    return render(request, 'fundooapp/index.html', {}, response)
                else:
                    return HttpResponse("Your account was inactive.")
            else:
                print("Someone tried to login and failed.")
                print("They used username: {} and password:{}".format(username, password))
                return HttpResponse("Invalid login details given")
        except:
            return render(request, 'fundooapp/user_login.html', {})
    else:
        return render(request, 'fundooapp/user_login.html', {})


def activate(request, uidb64, token):
    """this method is used to generate confirmation mail to the user"""
    try:
        # uid: The user’s primary key encoded in base 64
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        # We check the token validation
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return HttpResponse('Thank you for your email confirmation. '
                            'Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


class UserViewSet(viewsets.ModelViewSet):
    """This Class is used to create the user Api Endpoints"""
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserDetailSerializer
print("UserViewSet:", UserViewSet.__doc__)

""" This method is used to display all users list"""
@method_decorator(app_login_required)
def get_users():
    # or simply .values() to get all fields
    users = User.objects.all().values().order_by('-date_joined')
    users_list = list(users)
    return JsonResponse(users_list, safe=False)


#*********************************Registration for User using Rest API******************************
class RestUserRegister(CreateAPIView):
    """ This class is used for Register the rest User and create the JWT Token"""
    serializer_class = RegisterSerializer

    @method_decorator(app_login_required)
    def post(self, request, *args, **kwargs):
        res = {"message": "something bad happened",
               "data": {},
               "success": False}
        try:
            username = request.data['username']  # getting the username
            email = request.data['email']   # getting the email id
            password = request.data['password']     # getting the password
            if username and email and password is not "":   # condition
                user = User.objects.create_user(username=username, email=email, password=password)
                user.is_active = False
                user.save()
                message = render_to_string('fundooapp/acc_active_email.html', {
                    'user': user,
                    'domain': 'localhost:8000',
                    # takes user id and generates the base64 code(uidb64)
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                    # Here we receive uidb64, token. By using the "urlsafe_base64_decode"
                    # we decode the base64 encoded uidb64 user id.
                    # We query the database with user id to get user
                    'token': account_activation_token.make_token(user),
                    # takes the user object and generates the onetime
                    # usable token for the user(token)
                })
                mail_subject = 'Activate your account...'
                to_email = email
                send_email = EmailMessage(mail_subject, message, to=[to_email])
                send_email.send()
                if send_email:
                    payload = {'username': username, 'password': password, 'email':email}
                    jwt_token = {

fundoonote/fundooapp/templates/fundooapp/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'fundooapp:activate' uidb64=uid token=token %}
{% endautoescape %}

fundoonote/fundooapp/templates/fundooapp/base.html
{% load static from staticfiles %}
<body>
    <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'fundooapp/css/style.css' %}"/>
    </head>
  <body background="{% static "fundooapp/images/image.jpg" %}" alt="My image">
    <div class="navbar">
{# Django Home Link / Admin Link / Register Link#}
          <a class="navbar-brand" href="{% url 'home' %}">FundooApp</a>
          <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a>
          <a class="navbar-brand" href="{% url 'api_docs' %}">Swagger</a>
          <a class="navbar-brand" href="{% url 'fundooapp:register' %}"><span class="glyphicon glyphicon-user"></span> Register</a>
          <a class="navbar-brand" href="{% url 'password_reset' %}">ResetPassword</a>

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'logout' %}">Logout</a>
            <a class="navbar-brand" href="{% url 'enter' %}">Enter  </a>
          {% else %}
            <a class="navbar-brand" href="{% url 'fundooapp:login' %}">
                <span class="glyphicon glyphicon-log-in"></span>  Login </a>
          {% endif %}
      </div>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
</body>

fundoonote/fundooapp/templates/fundooapp/hello.html
Welcome to BridgeLabz..!!..

fundoonote/fundooapp/templates/fundooapp/home.html
{% extends "fundooapp/base.html" %}
{% block body_block %}
<style>
    p,h2{
     font-style: italic;
     color:brown;
   }
</style>
<body>
<marquee direction="right"><p>If You forgot your password just click on above <span>ResetPassword</span> Link</p></marquee>
<div class="container" style="back">
    <br><br><br><br><br><p align="left" style="font-size:50px">Welcome to the FundooNote!!! </p>
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-sm-12 mb-3">
            <h2 class="text-center"> Welcome {{ user.username }} </h2>
        </div>
        {% for ass in backends.associated %}
          {% if ass.provider == 'facebook' %}
            <div class="col-md-6 text-center">
                <img src="{{ass.extra_data.picture.data.url}}" alt="" width="150" height="150" style="border-radius: 50%">
            </div>
            <div class="col-md-6 social-container my-2">
                <p> Signed in via:  {{ ass.provider }} </p>
                <p> Name:  {{ ass.extra_data.name }} </p>
                <p> Provider url: <a href="{{ass.extra_data.profile_url}}">link</a></p>
            </div>
          {% endif %}
        {% if ass.provider == 'linkedin-oauth2' %}
            <div class="col-md-6 text-center">
                <img src="{{ass.extra_data.picture.data.url}}" alt="" width="150" height="150" style="border-radius: 50%">
            </div>
            <div class="col-md-6 social-container my-2">
                <p> Signed in via:  Linkedin </p>
                <p> Name:  {{ ass.extra_data.name }} </p>
                <p> Provider url: <a href="{{ass.extra_data.profile_url}}">link</a></p>
            </div>
          {% endif %}
       {% endfor %}
        <div class="col-sm-12 mt-2 text-center">
        </div>
    {% else %}
        <br><br><br><h2 align="right">Register or Login if you'd like to..</h2>
    {% endif %}
{% endblock %}
</body>

fundoonote/fundooapp/templates/fundooapp/index.html
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'fundooapp/css/style.css' %}"/>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} </title>
</head>
<body background="{% static "fundooapp/images/image3.jpeg" %}" alt="My image">
<div class="navbar">
<a class="navbar-brand"  href="{% url 'logout' %}">Logout</a>
<a class="navbar-brand" href="{% url 'password_reset' %}">ResetPassword</a>
</div>

<br><br><br><br><h1 align="center"> Welcome {{ user.username }}<br>
    <i class="glyphicon glyphicon-thumbs-up" style="font-size:64px"></i>

</h1><br><br>
{% block content %}
{% endblock %}
</body>
</html>

fundoonote/fundooapp/templates/fundooapp/login.html
{% extends 'loginapp/base.html' %}
{% load staticfiles %}
{% block title %} Sign in {% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'fundooapp/css/style.css' %}"/>

<body background="{% static "fundooapp/images/image3.jpeg" %}" alt="My image">
<h1>Login Here</h1><hr>
      <hr>
<form method="post" action="{% url 'fundooapp:user_login' %}">
       {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input id="user" type="text" name="username" placeholder="Username" size="20px" align="center">
    <br><br>
<label for="password">Password:</label>
          <input id="pwd" type="password" name="password" placeholder="Password" size="20px">
    <br><br>
<input id="sub" type="submit" name="" value="Login" size="30px" height="10px" width="10px">
</form>

<hr><hr>
<h1> Social Account Login</h1>

<li>
 <ul><button class="btn btn-primary mb-2">
     <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
 </button></ul>
     <ul><button class="btn btn-info mb-2">
           <a href="{% url 'social:begin' 'linkedin-oauth2' %}">Login with LinkedIn</a>
     </button></ul>
     <ul>
         <button class="btn btn-info mb-2" style="size:20px">
           <a href="{% url 'social:begin' 'github' %}">Login with github</a>
     </button>
     </ul></li>
{% endblock %}
</body>

fundoonote/fundooapp/templates/fundooapp/password_reset_complete.html
{% extends 'fundooapp/base.html' %}
<!--
Page displayed to the user after the password was successfully changed.
-->
{% block content %}
  <p>
    Your password has been set. You may go ahead and
    <a href="{% url 'fundooapp:user_login' %}">sign in</a> now.
  </p>
{% endblock %}

fundoonote/fundooapp/templates/fundooapp/registration.html
{% load static %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'fundooapp/css/style.css' %}"/>

{% block body_block %}

<body background="{% static "fundooapp/images/b.jpg" %}" alt="My image">
<div class="container">
    <div class="jumbotron">

        {% if registered %}
        <h1>Thank you for registering!</h1>
        {% else %}
        <h1 style="color:black">Register Here</h1>
        <hr style="color:black">
        <div id="div1">
            <form enctype="multipart/form-data" method="POST" style="color:Black">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input id="sub1" type="submit" name="" value="Register">
            </form>
        </div>

    </div>

    {% endif %}

</div>

</body>
{% endblock %}

fundoonote/fundooapp/templates/fundooapp/search.html
<form method="get">
    <input id="q" name="q"  type="text" placeholder="Search your input">
</form>
{% for item in notes %}
title: {{ item.title }}<br>
id: {{ item.id }}<br>
color: {{ item.color }}<br>
image: {{ item.image }}<br>
<br>
{% endfor %}

fundoonote/fundooapp/templates/fundooapp/user_login.html
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" href="{% static 'fundooapp/css/style.css' %}"/>
<body background="{% static "fundooapp/images/image3.jpeg" %}" alt="My image">
<h1>Login Here</h1><hr><hr>
<form method="POST" action="{% url 'fundooapp:login' %}">
       {% csrf_token %}
       {# A more "HTML" way of creating the login form#}
       <label for="username">Username:</label>
       <input id="user" type="text" name="username" placeholder="Username" size="20px" align="center">
      <br><br>
<label for="password">Password:</label>
    <input id="pwd" type="password" name="password" placeholder="Password" size="20px">
    <br><br>
   <input id="sub" type="submit" name="" value="Login" size="30px" height="10px" width="10px">
</form>

<hr><hr>
<h1> Social Account Login</h1>

<li>
 <ul><button class="btn btn-primary mb-2">
     <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
 </button></ul>
     <ul><button class="btn btn-info mb-2">
           <a href="{% url 'social:begin' 'linkedin-oauth2' %}">Login with LinkedIn</a>
     </button></ul>
     <ul>
         <button class="btn btn-info mb-2" style="size:20px">
           <a href="{% url 'social:begin' 'github' %}">Login with github</a>
     </button>
     </ul></li>
{% endblock %}
</body>