fundoonote/Users/urls.py
from django.conf.urls import include,url
from . import views
from django.urls import path
from django.contrib import admin

app_name = 'Users'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/$', views.register, name='register'), # url for register
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    views.activate, name='activate'),# url activate the user registration
    url('rest_login/', views.RestLogin.as_view(), name='rest_login'),
    # list of Notes URL
    path("Notes/List/", views.NotesList.as_view(), name="note_list"),
    path("Notes/Detail/<int:pk>/", views.NotesDetail.as_view(), name="note_detail"),
    path("Notes/Create/", views.CreateNotes.as_view(), name="note"),
    path("Notes/Delete/<int:pk>/", views.NotesDelete.as_view(),name='delete'),
    path("Notes/Trash/<int:pk>/", views.TrashView.as_view(), name='trash'),
    path("Notes/Archive/<int:pk>/", views.ArchiveNotes.as_view(), name='archive'),
    path("Notes/ArchiveList/", views.ArchiveList.as_view(), name='archive'),
    path("Notes/Reminder/<int:pk>/", views.ReminderNotes.as_view(), name='reminder'),
    path("Notes/TrashList/<trash>", views.TrashList.as_view(), name='trash_list'),
    path("Notes/Pagination/", views.NotesListPage.as_view(), name="note_list"),

    # List of label URL
    path("Label/List/", views.LabelList.as_view(), name="label_list"),
    path("Label/Detail/<int:pk>/", views.LabelDetail.as_view(), name="label_detail"),
    path("Label/Create/", views.CreateLabel.as_view(), name="label"),
    path("Label/Delete/<int:pk>/", views.LabelDelete.as_view(), name='delete'),
    url(r'^search/', views.search, name='search'),
]

fundoonote/fundoonote/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view
from rest_framework_simplejwt import views as jwt_views
from fundooapp import views
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet) # register the view_set to display the all users
router.register(r'Search/elastic_search',views.NotesDocumentViewSet,basename='elastic_search')
schema_view = get_schema_view(title='Pastebin API')
urlpatterns = [
    url('^schema/', schema_view),
    url('^', include('fundooapp.urls')), # include the all app urls in project urls
    url(r'^register/$', views.register, name='register'),  # url for register
    url(r'^admin/', admin.site.urls), # admin login urls in rest Format
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^$', views.home, name='home'), # index url is call the template
    url(r'^enter/', views.enter, name='enter'), # enter is html template urls
    url(r'^', include(router.urls)), # include the router url to use the display all users
    url(r'^api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^get_users/',views.get_users), # this view_url is display the all users in JSOn format
    url(r'^social-auth/', include('social_django.urls', namespace="social")),
    url(r'^',include('rest_framework.urls', namespace='rest_framework')),
    url(r'^swagger/$', get_swagger_view(title='API Docs'), name='api_docs'), # swagger
    url(r'^api/', include_docs_urls(title='Notes API'), name='api'), # CoreApi
    url(r'^',include('django.contrib.auth.urls')),


]

fundoonote/Users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

validate_alphanumeric = RegexValidator(r'^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.')
validate_alphabetical = RegexValidator('^[a-zA-Z]', 'Only Alphabetical Characters are allowed.')
class Notes(models.Model):
    title = models.CharField(max_length=400, validators=[validate_alphanumeric])
    description = models.CharField(max_length=100, validators=[validate_alphabetical])
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now=True)
    remainder = models.DateTimeField(default=None, null=True, blank=True)
    is_archive = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    COLOR_CHOICES = (
        ('R','Red'),
        ('G','Green'),
        ('B','Blue'),
    )
    color = models.CharField(default='Green', max_length=50, blank=True,choices=COLOR_CHOICES, null=True)
    image = models.ImageField(default=None, null=True)
    trash = models.BooleanField(default=False)

    def __str__(self):  # print string Format
        return self.title

""" Label Models"""
class Label(models.Model):
    text = models.CharField(max_length=100, validators=[validate_alphabetical])
    pub_date = models.DateTimeField(auto_now=True)

    def __str__(self): # print string Format
        return  self.text

fundoonote/Users/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm): # UserForm is created the form
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(max_length=200)
    class Meta:
        model = User
        fields = ('username','first_name','last_name','password', 'email')

fundoonote/Users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.models import User

from rest_framework.generics import CreateAPIView, ListCreateAPIView
from rest_framework import viewsets, generics  # viewSet is collection of Users
from .tokens import account_activation_token # activate the users account
from .serializers import UserSerializer # import the user serializer to serialize the User data
from .redis import redis_methods  # import the redis_method class from redis file
from .forms import UserForm
from django.shortcuts import render
from .documents import PostDocument
from django.db.models import Q

from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from .models import Notes, Label
from .serializers import NotesSerializer, LabelSerializer
import pickle

from rest_framework.pagination import PageNumberPagination
from django_filters.rest_framework import DjangoFilterBackend
import jwt


r = redis_methods()
"""this method is used to display the home page"""
def home(request):
    return render(request, 'loginapp/home.html', {})


"""this method is used to enter the Users"""

def enter(request):
      return render(request, 'loginapp/index.html', {})

# def keep(request):
#     return render(request, 'Users/base.html',{})

"""only after login of user this method can be called"""
def user_logout(request):  # this method is used to logout
    logout(request)
    return HttpResponseRedirect(reverse('home')) # after logout user reverse the index



"""this method is used to signup the user"""
def register(request):      # this method is used to signup the user
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('loginapp/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                # takes user id and generates the base64 code(uidb64)
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                # Here we receive uidb64, token. By using the "urlsafe_base64_decode"
                # we decode the base64 encoded uidb64 user id.
                # We query the database with user id to get user
                'token': account_activation_token.make_token(user),
                # takes the user object and generates the onetime usable token for the user(token)
            })
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')

    else:
        user_form = UserForm()

    return render(request, 'loginapp/registration.html',
                           {'user_form': user_form})


"""this method is used to login the user"""
@login_required
def user_login(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # authentication of user name and password
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return render(request, 'loginapp/index.html', {})
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'loginapp/login.html', {})


"""this method is used to generate confirmation mail to the user"""

def activate(request, uidb64, token):   # this method is used to generate confirmation mail to the user
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))  # uid: The user’s primary key encoded in base 64.
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        # We check the token validation
        user.is_active = True
        user.save()
        login(request, user ,backend='django.contrib.auth.backends.ModelBackend')
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

"""
This class is used to display the all users in rest_framework
"""
class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
print(UserViewSet.__doc__)

"""
this class is used for login the rest and create the JWT Token 
 and store the token in redis cache
"""
class RestLogin(CreateAPIView):
    # account and create the JWT token
    serializer_class = UserSerializer
    def post(self, request, *args, **kwargs):
        res = {"message": "something bad happened", # give the element what you want in rest api
               "data": {},
               "success": False,
               }
        try:
            username = request.data['username']
            if username is None:                   # if username is None
                raise Exception("Username is required") # raise exception Username is required
            password = request.data['password']
            if password is None:
                raise Exception("password is required")
            user = authenticate(username=username, password=password) #validate the password
            print('user-->', user)
            if user:
                if user.is_active:  # check if the user is active or not.
                    payload = {'username': username, 'password': password}
                    jwt_token = {
                        'token': jwt.encode(payload, "Cypher", algorithm='HS256').decode('utf-8')
                    }
                    print(jwt_token)  # print JWT Token
                    """ JWT token stored in cache"""
                    token = jwt_token['token']
                    r.set_token("p3", token) # set the token in redis cache
                    token_val = r.get_token("p3") # get the value of token from cache
                    print("Display The Tokens using get_token()")
                    print(token_val)# print the cache token
                    print("Display the length of Token")
                    len_str = r.length_str("p3")
                    print(len_str) # returns the length of token
                    res['message'] = "Logged in Successfully"
                    res['data'] = token
                    res['success'] = True
                    return Response(res)  # if active then return response with jWT Token
                else:
                    return Response(res) # else user is not active
            if user is None:
                return Response(res)  # else user is not exist
        except Exception as e:
            print(e)
            return Response(res) #print response as is

""" This method is used to display the all users in JSOn Format"""
def get_users():
    users = User.objects.all().values().order_by('-date_joined')  # or simply .values() to get all fields
    users_list = list(users)
    return JsonResponse(users_list, safe=False)


""" ****************************Curd Operation for Notes*************************** """

"""Create the Notes"""
class CreateNotes(CreateAPIView):
    serializer_class = NotesSerializer

"""Display the list of Notes"""
class NotesList(APIView):
    try:
        def get(self,request):
            notes = Notes.objects.all()
            data = NotesSerializer(notes, many=True).data
            return Response(data)
    except Exception as e:
        print("Invalid Function")

""" Display the details of list"""
class NotesDetail(APIView):
    try:
        def get(self, request, pk):
            note = get_object_or_404(Notes, pk=pk)
            data = NotesSerializer(note).data
            dict = pickle.dumps(data)  # dump the file
            r.set_token('mydict', dict) # stored the value into key
            print("set data")
            read_dict = r.get_token('mydict')  # read the value
            data1 = pickle.loads(read_dict)  # loads data disk into data1
            print(data1)
            return Response(data)
    except Exception as e:
        print("Something is Happen")

""" Delete the Node """
class NotesDelete(APIView):
    def get(self, request, pk):
        note = Notes.objects.get(pk=pk)
        print(pk)
        try:
            if note.deleted == True:  # if deleted field is true.
                data = note.delete()  # if true then delete
                print(data)
            return Response("Delete the Item")
        except Exception as e:
            print(e)

""" Trash the Note"""
class TrashView(APIView):

fundoonote/Users/templates/loginapp/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'Users:activate' uidb64=uid token=token %}
{% endautoescape %}

fundoonote/Users/templates/loginapp/base.html
{% load static from staticfiles %}
<html>
    <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'loginapp/css/style.css' %}"/>

  <body background="{% static "loginapp/images/image.jpg" %}" alt="My image">
     <div class="navbar">

{# Django Home Link / Admin Link / Register Link#}
         <a class="navbar-brand" href="{% url 'home' %}">MyApp</a>
          <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
          <a class="navbar-link" href="{% url 'Users:register' %}">
              <span class="glyphicon glyphicon-user"></span> Register</a>
          <a target="_blank" href="{% url 'api_docs' %}">API Docs</a>

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
            <a href="{% url 'enter' %}">Enter  </a>
          {% else %}
            <a class="navbar-link" href="{% url 'Users:user_login' %}">
                <span class="glyphicon glyphicon-log-in"></span>  Login </a>
            <a class="navbar-link" href="{% url 'password_reset' %}">ResetPassword</a>
          {% endif %}
      </div>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
    </body>
</html>

fundoonote/Users/templates/loginapp/home.html
{% extends "loginapp/base.html" %}
{% block body_block %}
<style>
    p,h2{
     font-style: italic;
     color:brown;

   }
</style>
<body>
<marquee direction="right"><p>If You forgot your password just click on above <span>ResetPassword</span> Link</p></marquee>
<div class="container" style="back">
    <br><br><br><br><br><p align="left" style="font-size:50px">Welcome to the FundooApp!!! </p>
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-sm-12 mb-3">
            <h2 class="text-center"> Welcome {{ user.username }} </h2>
        </div>
        {% for ass in backends.associated %}
          {% if ass.provider == 'facebook' %}
            <div class="col-md-6 text-center">
                <img src="{{ass.extra_data.picture.data.url}}" alt="" width="150" height="150" style="border-radius: 50%">
            </div>
            <div class="col-md-6 social-container my-2">
                <p> Signed in via:  {{ ass.provider }} </p>
                <p> Name:  {{ ass.extra_data.name }} </p>
                <p> Provider url: <a href="{{ass.extra_data.profile_url}}">link</a></p>
            </div>
          {% endif %}
        {% if ass.provider == 'linkedin-oauth2' %}
            <div class="col-md-6 text-center">
                <img src="{{ass.extra_data.picture.data.url}}" alt="" width="150" height="150" style="border-radius: 50%">
            </div>
            <div class="col-md-6 social-container my-2">
                <p> Signed in via:  Linkedin </p>
                <p> Name:  {{ ass.extra_data.name }} </p>
                <p> Provider url: <a href="{{ass.extra_data.profile_url}}">link</a></p>
            </div>
          {% endif %}
       {% endfor %}
        <div class="col-sm-12 mt-2 text-center">
        </div>
    {% else %}
        <br><br><br><h2 align="right">Register or Login if you'd like to..</h2>
    {% endif %}
{% endblock %}
</body>

fundoonote/Users/templates/loginapp/index.html
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'loginapp/css/style.css' %}"/>

    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} </title>
</head>
<body background="{% static "loginapp/images/image3.jpeg" %}" alt="My image">
 <div class="navbar">
<a href="{% url 'logout' %}">Logout</a>
<a class="navbar-link" href="{% url 'password_reset' %}">ResetPassword</a>
 </div>

<br><br><br><br><h1 align="center"> Welcome {{ user.username }}<br>
    <i class="glyphicon glyphicon-thumbs-up" style="font-size:64px"></i>

</h1><br><br>

{% block content %}
{% endblock %}
</body>
</html>

fundoonote/Users/templates/loginapp/login.html
{% load staticfiles %}

        <link rel="stylesheet" href="{% static 'loginapp/css/style.css' %}"/>

{% block body_block %}



<body background="{% static "loginapp/images/image3.jpeg" %}" alt="My image">
<h1>Login Here</h1><hr>
      <hr>
<form method="post" action="{% url 'Users:user_login' %}">
       {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input id="user" type="text" name="username" placeholder="Username" size="20px" align="center">
    <br><br>
<label for="password">Password:</label>
          <input id="pwd" type="password" name="password" placeholder="Password" size="20px">
    <br><br>
<input id="sub" type="submit" name="" value="Login" size="30px" height="10px" width="10px">
</form>
<hr><hr>
<h1> Social Account Login</h1>

<li>
 <ul><button class="btn btn-primary mb-2">
     <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
 </button></ul>
     <ul><button class="btn btn-info mb-2">
           <a href="{% url 'social:begin' 'linkedin-oauth2' %}">Login with LinkedIn</a>
     </button></ul>
     <ul><button class="btn btn-info mb-2" style="size:20px">
           <a href="{% url 'social:begin' 'github' %}">Login with github</a>
     </button></ul></li>
{% endblock %}
</body>

fundoonote/Users/templates/loginapp/password_reset_complete.html
{% extends 'loginapp/base.html' %}
<!--
Page displayed to the user after the password was successfully changed.
-->
{% block content %}
  <p>
    Your password has been set. You may go ahead and
    <a href="{% url 'loginapp:user_login' %}">sign in</a> now.
  </p>
{% endblock %}

fundoonote/Users/templates/loginapp/password_reset_confirm.html
{% extends 'loginapp/base.html' %}

{% block content %}
{% if validlink %}
<h3>Change password</h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change password</button>
</form>
{% else %}
<p style="italic">
    The password reset link was invalid, possibly because it has already been used.
    Please request a new password reset.
</p>
{% endif %}
{% endblock %}

fundoonote/Users/templates/loginapp/password_reset_done.html
{% extends 'loginapp/base.html' %}
{% load staticfiles %}
{% block content %}      <!--Page displayed to the user after submitting the email form-->.

<body background="{% static " loginapp/image3.jpeg" %}" alt="My image">
<p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
</p>
<p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
</p>
{% endblock %}

fundoonote/Users/templates/loginapp/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The TestSite Team
{% endautoescape %}

fundoonote/Users/templates/loginapp/password_reset_form.html
{% extends 'loginapp/base.html' %}
{% load staticfiles %}

        <link rel="stylesheet" href="{% static 'loginapp/css/style.css' %}"/>

{% block content %}   <!--Form where the user submit the email address-->

<h3>Forgot password</h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
</body>
{% endblock %}

fundoonote/Users/templates/loginapp/registration.html
{% load static %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'loginapp/css/style.css' %}"/>

{% block body_block %}

<body background="{% static "loginapp/images/b.jpg" %}" alt="My image">
<div class="container">
    <div class="jumbotron">

        {% if registered %}
        <h1>Thank you for registering!</h1>
        {% else %}
        <h1 style="color:black">Register Here</h1>
        <hr style="color:black">
        <div id="div1">
            <form enctype="multipart/form-data" method="POST" style="color:Black">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input id="sub1" type="submit" name="" value="Register">
            </form>
        </div>

    </div>

    {% endif %}

</div>

</body>
{% endblock %}